### ISSUE TITLE
Assets files are not served

### ISSUE THREAD

**Issue by mgite** [42wim/caddy-gitea#7]
I am using traefik for gitea container to have proper https. Since i do not have exposed it to the internet i used DuckDNS dns challenge to have https configured. This works for gitea and for all the other containers i have.

I have gitea and CI which builds repo gitea-pages using mkdocs for website it has gitea-pages branch and also topic with this name as it was described in this projects guide.

I configured domain for this service as usual in labels of docker-compose file for it for traefik
first org is my organization name
```
- traefik.enable=true
- traefik.http.routers.caddygitea.rule=Host(\org.mydomain.duckdns.org`)`
- traefik.http.routers.caddygitea.entrypoints=websecure
- traefik.http.services.caddygitea.loadbalancer.server.port=3000
```

And Caddyfile for caddy-gitea is this:

```
{
  order gitea before file_server
}

:3000 {
  gitea {
    server http://gitea:3000
    token 3944d6d1833d56b9e55af6055f5424c7133418ef
    #domain mydomain.duckdns.org # Uncomment and configure if needed
  }
}
```

It serves index.html for / but assets are not served properly. If i click on link in documentation subpath index.htmls are not even served. It shows just a white page. Here is an error from inspect element of browser when i open / and assets are not served.

```
GET https://org.mydomain.duckdns.org/assets/stylesheets/main.50c56a3b.min.css
GET https://org.mydomain.duckdns.org/assets/stylesheets/palette.06af60db.min.css
GET https://org.mydomain.duckdns.org/assets/javascripts/bundle.c18c5fb9.min.js
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
Empty string passed to getElementById().
GET https://org.mydomain.duckdns.org/assets/javascripts/bundle.c18c5fb9.min.js
Loading failed for the <script> with source “https://org.mydomain.duckdns.org/assets/javascripts/bundle.c18c5fb9.min.js”.
GET https://org.mydomain.duckdns.org/assets/images/favicon.png
```

How can i fix it?

**Comment by ascendise** [comment]
Hey I ran into the same issue as you!

# Use Case

I have a project with a `main` branch for code and an orphan `gitea-pages`-branch for my generated docs. I want to access sites via `username.gitea-pages.domain.tld/my-project/?ref=gitea-pages`

# Problem
The `index.html` file will get served but all assets will fail to load with `404`. The reason is, the subsequent requests for the assets do not contain the `?ref` parameter and therefore `caddy-gitea` tries to load the assets from the `master` branch

## Repro

I have a repro here: https://gitea.ascendise.ch/ascendise/caddy-gitea-bug-repro

I have the branches `master` and `gitea-pages`. For `gitea-pages` I renamed the asset-file so it won't just load it from `master` (that confused me for a moment😄) 

When trying to access the site on `master` (default) the css gets loaded and the background is green🥳:
https://ascendise.gitea-pages.ascendise.ch/caddy-gitea-bug-repro/  

When trying to access the site on `gitea-pages` (`?ref=gitea-pages`) the browser will request the css from "https://ascendise.gitea-pages.ascendise.ch/caddy-gitea-bug-repro/styles/index-gitea-pages.css" (notice the missing ?ref) and therefore won't find the file.
https://ascendise.gitea-pages.ascendise.ch/caddy-gitea-bug-repro/?ref=gitea-pages

# Solutions

Easiest solution without changing anything is to just put your site on `master`.

A quick solution would be to be able to define the default reference used. Most people would not use the current default (`master`) anyway as most use `main`.

I don't know how to solve the problem and still be able to access different references via query-parameter. It would probably make less problems if the reference could be specified in the path too. `\my-project\ref\index.html`

**Comment by mgite** [comment]
I think this repo is dead. I hope gitea comes up with working github pages like solution.

**Comment by ascendise** [comment]
Yeah, looks like it which is kind of a bummer as this is the only (easy to use) solution for Gitea Pages I could find. I would be interested in fixing some of the stuff (at least the things that are blocking me).
I may try a PR for the default reference thing I mentioned, to have an easy workaround for this issue.
Worst case, @42wim abandoned the project. Then I'll just use my fork :smile:

**Comment by mgite** [comment]
You can do what i did for my solution. I use mkdocs to build documentation and simply build using CI docker image nginx including and run it for pages. It's pretty simple to do. I can send you workflow.yml and Dockerfile if you need it.

**Comment by ascendise** [comment]
Don't worry, will work it out myself somehow, else where is the fun in it :smile:
But thank you very much!
